### ISSUE TITLE
[ISSUE] [Doc] Wiki example reproduction issues

### ISSUE THREAD

**Issue by kparichay** [nnsuite/nnstreamer#1107]
There are additional requirements for the [example](https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots) to run. (https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots)
- libgstreamer1.0-dev
- libgstreamer-plugins-base1.0-dev
- libopencv-dev
- gstreamer1.0-tools
- libgtest-dev (optional to satisfy all the dependencies of the meson build for nnstreamer)

These can be added in the dependency list.
This was checked by following the wiki page on a fresh installation of 16.04.5

Building nnstreamer-example.git from the same page gives an error in ninja install step:
```
ccache cc -I -Inative/example_speech_command_tensorflow_lite/7655781@@nnscustom_speech_command_tflite@sha -Inative/example_speech_command_tensorflow_lite -I../native/example_speech_command_tensorflow_lite -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu89 -g -fPIC  -MD -MQ 'native/example_speech_command_tensorflow_lite/7655781@@nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o' -MF 'native/example_speech_command_tensorflow_lite/7655781@@nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o.d' -o 'native/example_speech_command_tensorflow_lite/7655781@@nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o' -c ../native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c
../native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c:18:45: fatal error: nnstreamer/tensor_filter_custom.h: No such file or directory
```

I was able to resolve issue by adding $NNST_ROOT/include in the include list for the compilation in build/build.ninja. It is a temporary solution as build.ninja is overwritten by meson. I am getting familiar with meson build process to identify the source of the issue.

Lastly, the meson build process does not identify the local installation of the libraries for python (installations in $HOME/.local). I am not sure if the this is the desired behavior.

**Comment by kparichay** [comment]
Yes, as you said - 
$NNST_ROOT/lib/pkgconfig should be added to PKG_CONFIG_PATH
Further, nnstreamer needs to be added as a dependency in the meson.build of nnstreamer-example.git

I tried building with this way and it works. Should I open a PR for this?

**Comment by kparichay** [comment]
I tried adding `$NNST_ROOT/lib/pkgconfig` to the `PKG_CONFIG_PATH` but could not solve the error.
I also tried adding `nnstreamer` as a dependency, adding the `includedir` from `nnstreamer.pc` using `include_subdirectories` and including it in the `meson.build` of example_speech_command_tensorflow_lite. But even this did resolve the issue.

**Comment by hjbc0921** [comment]
I am going through the same problem. nnstreamer.pc is also generated in $NNST_ROOT/build, so I tried this one as PKG_CONFIG_PATH, but no progress.
nnstreamer.pc file seems to be generated correctly.

Any updates in this issue?
(me and my teammate are trying to update wiki pages, including this issue. If it is already in progress, let me know.)

**Comment by myungjoo** [comment]
I believe @kparichay is not experiencing the issue because he's good with the build and testing.

If you experience similar issues, please post with the full related information here.

Plus, if you are going to build some other applciation (including nnstreamer-example.git), I recommend you to install nnstreamer and its devel files (e.g., create .deb files with ```debuild -uc -us``` in Ubuntu, and install the generated .deb files)

**Comment by myungjoo** [comment]
> I am going through the same problem. nnstreamer.pc is also generated in $NNST_ROOT/build, so I tried this one as PKG_CONFIG_PATH, but no progress.

This is because the paths in nnstreamer.pc is configured for installation and you didn't install it properly, yet. You need to install the built binaries to the configured paths before refering it from applications.

**Comment by hjbc0921** [comment]
Using debuild, this issue was not repeated, so I will continue development with this settings. Thank you for your fast feedback and advice.

Meanwhile, using meson build, this issue still remains.
Problem is with including $NNST_ROOT/include/nnstreamer/tensor_filter_custom.h. 
```
../native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c:18:45:
fatal error: nnstreamer/tensor_filter_custom.h: No such file or directory
```
I think these header files are not related with installation, can you be more specific with 

> install the build binaries to the configured paths

?

By checking with `pkg-config --libs --cflags nnstreamer` pkg-config finds nnstreamer.pc well, with correct path to header files. (I exported correct PKG_CONFIG_PATH.)
However, when I add nnstreamer as dependency in meson.build, it can not find native dependency. 

If I comment out speech subdir in meson build, everything works fine.

**Comment by wooksong** [comment]
@hjbc0921 The reason why you are getting such build error is because 'nnstreamer-example'  has a build-time dependency on the nnstreamer development kit (a.k.a 'nnstreamer-dev') package. In other word, this is because you simply have no 'nnstreamer/tensor_filter_custom.h' in your standard include path (/usr/include, maybe) or you simply did not indicate the directory where 'nnstreamer/tensor_filter_custom.h' is included in. 

## Reproduction of Issue ##
```bash
[19:41:53-wook@SERVER]~/Work/nnstreamer-example  (master) $ meson build
The Meson build system
Version: 0.45.1
Source dir: /home/wook/Work/nnstreamer-example
Build dir: /home/wook/Work/nnstreamer-example/build
Build type: native build
Project name: nnstreamer-example
Native C compiler: cc (gcc 5.5.0 "cc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010")
Native C++ compiler: c++ (gcc 5.5.0 "c++ (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.56.3
Native dependency gstreamer-1.0 found: YES 1.14.1
Native dependency gstreamer-base-1.0 found: YES 1.14.1
Native dependency gstreamer-video-1.0 found: YES 1.14.1
Native dependency gstreamer-audio-1.0 found: YES 1.14.1
Native dependency gstreamer-app-1.0 found: YES 1.14.1
Native dependency cairo found: YES 1.15.10
Library m found: YES
Library dl found: YES
Dependency threads found: YES
Native dependency tensorflow found: YES 1.9.0
Native dependency protobuf found: YES 3.6.1
Native dependency tensorflow-lite found: YES 0.1
Build targets in project: 10
Found ninja-1.8.2 at /usr/bin/ninja

[19:42:31-wook@SERVER]~/Work/nnstreamer-example  (master) $ ninja -C build/
ninja: Entering directory `build/'
[1/20] Compiling C object 'native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o'.
FAILED: native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o 
cc  -Inative/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite@sha -Inative/example_speech_command_tensorflow_lite -I../native/example_speech_command_tensorflow_lite -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu89 -O0 -g -fPIC -MD -MQ 'native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o' -MF 'native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o.d' -o 'native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite@sha/nnscustom_speech_command_tflite.c.o' -c ../native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c
../native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c:18:45: fatal error: nnstreamer/tensor_filter_custom.h: No such file or directory
compilation terminated.
[10/20] Compiling C++ object 'native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite@exe/nnstreamer_example_object_detection_tflite.cc.o'.
ninja: build stopped: subcommand failed.
```
## How to fix it ##
#### 0. Prelude ####
- Make sure that there is no 'tensor_filter_custom.h'
```bash
[19:42:35-wook@SERVER]~/Work/nnstreamer-example  (master) $ find /usr/include/ -name tensor_filter_custom.h
```
#### 1. Solution using the 'nnstreamer-dev' package (Ubuntu only) ####
- Add ppa:nnstreamer/ppa to your apt repository
```bash
$ sudo add-apt-repository ppa:nnstreamer/ppa
```
- Install nnstreamer-dev
```bash
$ sudo apt install nnstreamer-dev
```
- From now, you got 'nnstreamer/tensor_filter_custom.h' under your /usr/include
```bash
/usr/include/nnstreamer/tensor_filter_custom.h
```

#### 2. Solution using CFLAGS ####
- Remove 'nnstreamer-dev' (in case that you've already installed according to Solution 1
```bash
$ sudo apt purge nnstreamer-dev
$ find /usr/include/ -name tensor_filter_custom.h
```
- Cloning 'nnstreamer' from https://github.com/nnsuite/nnstreamer.git (If you've already forked and cloned it, you better to skip this part.)
```bash
$ pwd
/home/wook/Work/issue-1107
$ ls
nnstreamer-example

$ git clone https://github.com/nnsuite/nnstreamer.git

$ ls
nnstreamer  nnstreamer-example
$ cd nnstreamer-example/
$ pwd
/home/wook/Work/issue-1107/nnstreamer-example

$ CFLAGS=-I/home/wook/Work/issue-1107/nnstreamer/gst meson build
$ ninja -C build
```

**Comment by jaeyun-jung** [comment]
In ubuntu 16.04, simple way to define include path.
For example, 
```
~/.bashrc
export DEV_ROOT=/home/admin/dev    # set your path
export NNSTREAMER_CONF=$DEV_ROOT/nnstreamer.ini
export GST_PLUGIN_PATH=$GST_PLUGIN_PATH:$DEV_ROOT/lib/gstreamer-1.0
export C_INCLUDE_PATH=$C_INCLUDE_PATH:$DEV_ROOT/include
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$DEV_ROOT/include

# build nnstreamer and nnstreamer-example
$ $ meson --prefix=${DEV_ROOT} --sysconfdir=${DEV_ROOT} --libdir=lib --bindir=bin --includedir=include build
$ cd build
$ ninja install
```

**Comment by hjbc0921** [comment]
@wooksong Thank you for issue clarification! I should have done it, and I am sorry for the inconvenience. Clearly, I did not have tensor_filter_custom.h in /usr/include. This was because I used **nnstreamer**, not **nnstreamer-dev**, and I think this should be added to wiki (how to build for examples). I am planning to update some details in your wiki with my teammate, so if it is okay with you I will make PR to include this part in the wiki. 


When using **nnstreamer**, tensor_filter_custom.h is only at $NNST_ROOT/include, so normal build did not work. I used your second solution and it worked! Same with @jaeyun-jung. Thank you for detailed instruction. Your solution was exactly what I was looking for, and it worked like a charm. I think these two solutions also can be added to wiki as two alternatives, and if it is fine with you I will make PR and close this issue.

**Comment by wooksong** [comment]
@hjbc0921 Feel free to submit PR. It will be always welcome to help us by improving code and documents. As you know, this is open-source project:P

**Comment by myungjoo** [comment]
@kparichay Is this issue still valid?

**Comment by kparichay** [comment]
This issue has been resolved.
