### ISSUE TITLE
[Question] How is tensorflow-dev package generated ?

### ISSUE THREAD

**Issue by boxerab** [nnsuite/nnstreamer#1109]
I would like to build my own tensorflow-dev package, with GPU support. 

Thanks!

**Comment by myungjoo** [comment]
You need to look at tensorflow documentation and their source code.

However, in general for C/C++ programming, as long as the API set is the same,
you NEVER need "tensorflow-gpu-dev". Just slap in tensorflow-gpu (not dev) at run-time.

This is one of the reasons why we use shared-libraries (you can replace the implementation; gpu-build or cpu-build or whatsoever with the common "header" files, anytime)

**Comment by boxerab** [comment]
Thanks. I have another related question. Is there an advantage to using your own `tensorflow-devel` package instead of the tensorflow C API ?

https://www.tensorflow.org/install/lang_c

**Comment by myungjoo** [comment]
```tensorflow-dev``` package include tensorflow C API. So we are not using ```tensorflow-dev``` instead of tensorflow C API. Anyway, it appears that your questions is "Why are you using *-dev rpm/debu packaging instead of directly building from .git repo or pip install".

By using ```tensorflow-dev``` rpm/deb packaging, we can automate build and deploy processes for RPM (Tizen, Red Hat, SUSE, ...) or DEB (Ubuntu/Debian) systems. It also makes upgrade and uninstall processes automatic.

This approach is the standard and general method for Linux distros. The TensorFlow maintainers also know this and are trying to cooperate with Linux distro maintainers to deploy TensorFlow as rpm/deb packaging (which will include *-dev packages if they are sane enough).

**Comment by boxerab** [comment]
Thanks for the explanation. So, what steps do I need to take to create a `tensorflow-dev` package for the latest version of tensorflow ? Do you build from source ? Or do you take an existing package and re-package it ?

**Comment by myungjoo** [comment]
You can look it up at the deploying sites. For the .deb, look at https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+packages

For the .rpm, look at https://build.tizen.org/package/show/Tizen:Unified/tensorflow

There should be corresponding git URL and commit ID, which can be accessed from public IPs.

**Comment by boxerab** [comment]
Thanks, @myungjoo

**Comment by boxerab** [comment]
@myungjoo I checked out the repo - is it the tensorflow_deb branch I should be building ? And do I build with bazel ? I think it would be helpful to include this repo on the NNStreamer github page, along with instructions for how to build.

**Comment by myungjoo** [comment]
How to build tensorflow, How to package tensorflow for Ubuntu/Debian is to be discussed in tensorflow page. We have been working on it only because tensorflow is not yet "good enough" and anything we've done out of its main repo is considered to be temporary workaround. There is a google-group "tensorflow build", which exactly addresses what you want. Once they start to generate tensorflow packages properly (with devel packages for C/C++ APIs), we can remove all the workarounds.

Anyway, according to the PPA page, (you can browse it at launchpad.net), tensorflow in nnstreamer ppa uses recipe of https://code.launchpad.net/~nnstreamer/+recipe/tensorflow-daily , which uses sandbox/sangjung/launchpad_bugfix branch.

**Comment by boxerab** [comment]
Thanks for your help. I am not that familiar with debian packaging. Can I run this recipe on my local machine? I would like to build and package locally so that I get advantage of AVX2 vector instructions on CPU, which gives better performance.

**Comment by myungjoo** [comment]
Then, this ( https://github.com/nnsuite/nnstreamer/blob/master/Documentation/getting-started.md#clean-build-with-pdebuild-ubuntu-16041804 ) is what you want. With pdebuild, you can setup an isolated build environment that allows you to have the exactly same build enviornment with my machine or launchpad VM.

**Comment by boxerab** [comment]
Thanks. By the way, in Linux Self-Hosted Build section, you may want to mention in the wikie the branch that should be checked out for tensorflow - `launchpad_bugfix`

**Comment by boxerab** [comment]
That worked!  Thanks for your help, @myungjoo

**Comment by boxerab** [comment]
Unfortunately, I am getting the following error when trying to run the `Linux Self Hosted Build` for tensorflow using the instructions [here](https://github.com/nnsuite/nnstreamer/blob/master/Documentation/getting-started.md#clean-build-with-pdebuild-ubuntu-16041804): 

```
install -m 0644 tensorflow/contrib/lite/gen/lib/libtensorflow-lite.a /home/aaron/src/nnstreamer_local_build/tensorflow/debian/tmp/usr/lib/
install: cannot stat 'tensorflow/contrib/lite/gen/lib/libtensorflow-lite.a': No such file or directory
debian/rules:164: recipe for target 'install' failed
make: *** [install] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui failed
```

**Comment by myungjoo** [comment]
It means your tensorflow-dev package has not installed at the exact location where our tensorflow-dev packages does. Direct to your libtensorflow-lite.a via some variables in meson.build.

**Comment by boxerab** [comment]
Thanks. I uninstalled the debian packages from the PPA, deleted the PPA, and I am just trying to build the packages from source.  Does the self hosted build assume that I have already installed the PPA packages ?

**Comment by myungjoo** [comment]
Yes. Self-hosted build uses libraries and headers installed in our host (development PC). Thus, it requires you to have installed ALL the required packages in the system with appropriate paths and configurations (i.e., *.pc files). This holds for both approach1 and approach2.

**Comment by myungjoo** [comment]
As the discussion is no more continued, I'm closing this.
