### ISSUE TITLE
[CI/CD] Build failed on Launchpad

### ISSUE THREAD

**Issue by wooksong** [nnsuite/nnstreamer#1440]
- Build log
```bash
Test Group nnstreamer_filter_tensorflow Starts.
[FAILED][Critical] 1:gst-launch of case 1
[FAILED][Critical] 1:Golden test comparison
[FAILED][Critical] 2:gst-launch of case 2
[FAILED][Critical] 2:Golden test comparison
==================================================
[FAILED] Test Group nnstreamer_filter_tensorflow has failed cases (4)
```

Our amd64 build of nnstreamer (xenial/bionic) in launchpad has failed since at some point.

**Comment by again4you** [comment]
Architecture `amd64` and `armhf` are failed. 
* Detailed Log: https://launchpadlibrarian.net/423296474/buildlog_ubuntu-xenial-amd64.nnstreamer_0.1.3.0-0~201905111312~ubuntu16.04.1_BUILDING.txt.gz

**Comment by kparichay** [comment]
I am trying to upload pytorch debian to nnstreamer/ppa
Building pytorch for architecture `armhf` and `arm64` failed because building `nnstreamer` failed - detailed logs - https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+build/16798360/+files/buildlog_ubuntu-bionic-armhf.nnstreamer_0.1.3.0-0~201905151322~ubuntu18.04.1_BUILDING.txt.gz

The error however is different compared to the error in the log posted by @again4you

**Comment by kparichay** [comment]
The current error in nnstreamer launchpad for xenial is 
'''
The following packages have unmet dependencies:
 sbuild-build-depends-nnstreamer-dummy : Depends: meson (>= 0.40) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
apt-get failed.
Package installation failed
'''

**Comment by myungjoo** [comment]
Maybe... we need to build meson in launchpad/nnstreamer first.
It appears to emit errors in "test" stage; thus, the first workaround will be "disable test" in the meson debian build script.

**Comment by wooksong** [comment]
@nnsuite/nnstreamer Fixed! We can close this issue now.
