### ISSUE TITLE
[Tizen] Write Tensor_Filter::nnfw (2019.10.)

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#1677]
Write tensor_filter::nnfw that connects: https://review.tizen.org/gerrit/gitweb?p=platform/core/ml/nnfw.git;a=summary

It appears that it now has independent interfaces.

This is not for 5.5 M2, but 6.0 M1. However, this requires to be implemented during 2010.10~11.

The interface file is /runtime/include/nnfw.h
(Do not access other interfaces)

**Comment by myungjoo** [comment]
@kparichay Could you please share the status of tensor_filter::nnfw-runtime here?

**Comment by kparichay** [comment]
Issues related to running nnfw with cpu backend have been resolved
However, that patch has not been uploaded to main tizen repo
So, in order to test this patch, clone nnfw repo and build locally
Also, building nnfw repo installs libbackend_acl_cl.so in /usr/lib in emulator
Delete this file to test nnstreamer with cpu backend with nnfw successfully #1819 
This is because libbackend_acl_cl.so exists, but libOpencl is not

NYI items will be implemented this week

**Comment by myungjoo** [comment]
If there are pending nnfw commits and you need them, you can add nnfw at https://build.tizen.org/project/show/devel:AIC:Tizen:5.0:nnsuite and build the unmerged or un-SR-ed commit there for GBS in our CI server and your own PC.

**Comment by kparichay** [comment]
Managing backends will be done with #1849.
Close after #1842.
