### ISSUE TITLE
[Feature request] Support the `int8` tensor-type in TensorFlow Lite models

### ISSUE THREAD

**Issue by ajarthurs** [nnsuite/nnstreamer#2105]
**Is your feature request related to a problem? Please describe.**
I cannot run TensorFlow Lite models that contain `int8`-type tensors via `tensor_filter` and its TensorFlow Lite framework; however, I have no issue running models containing `uint8`-type tensors. If the model's input tensor-type is `int8`, NNStreamer throws the following negotiation error, erroneously reporting the model's input tensor-type to be `(null)`:
```
tensor_filter tensor_filter.c:557:gst_tensor_filter_configure_tensor:<tensorfilter0> The input tensor is not compatible.
0 : int8 [3:513:513:1] | (null) [3:513:513:1] FAILED
```
It's clear that NNStreamer does not yet support `int8` tensor types in TensorFlow Lite models. For example, [this function](https://github.com/nnsuite/nnstreamer/blob/e67091b777989bc0817ffb14d1e8d2cd51a43d15/ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc#L307:L333) does not map `kTfLiteInt8` to `_NNS_INT8`:
```
// ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
tensor_type
TFLiteInterpreter::getTensorType (TfLiteType tfType)
{
  switch (tfType) {
    case kTfLiteFloat32:
      return _NNS_FLOAT32;
    case kTfLiteUInt8:
      return _NNS_UINT8;
    case kTfLiteInt32:
      return _NNS_INT32;
    case kTfLiteBool:
    /** @todo insert `case kTfLiteInt8:` here */
      return _NNS_INT8;
    case kTfLiteInt64:
      return _NNS_INT64;
    case kTfLiteString:
    default:
      /** @todo Support other types */
      break;
  }

  return _NNS_END;
}
```

**Describe the solution you'd like**
Facilitate TensorFlow Lite models containing `int8`-type tensors: I already tried patching the mentioned `getTensorType` function. It resolved the said negotiation error but hangs during playback, so there is more patchwork required.

**Describe alternatives you've considered**
Strictly `uint8`-based quantized models, mostly available from TensorFlow's quantized stock models produced from quantization-aware training.

**Additional context**
According to [TensorFlow Lite's quantizaton specification](https://www.tensorflow.org/lite/performance/quantization_spec), signed 8-bit integers (`int8`) are preferred over unsigned integers (`uint8`). Their post-training quantization tool, for example, invariably produces `int8`-based models. Although their tool allows the user to specify other I/O types, including `uint8`, it inserts `Quantize` operators at the I/O and converts internal tensor-types to `int8`.

**Comment by myungjoo** [comment]
When we have first developed tensorflow-lite subplugin, we were based on Tensorflow 1.9, which didn't have int8 ( https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/lite/context.h ); thus we allocated nns-int8 for bool (we don't have bool-type in other/tensor type).

However, because modern tensorflow-lite (1.13~1.15) has more types including int8, we need to adjust this.

I'd suggest to add #if/#endif clauses with TensorFlow-Lite version conditions and add new types (and drop bool if it's >= 1.13. we may keep bool if it's >= 1.9 && <= 1.12).

1.13:
```
typedef enum {
  kTfLiteNoType = 0,
  kTfLiteFloat32 = 1,
  kTfLiteInt32 = 2,
  kTfLiteUInt8 = 3,
  kTfLiteInt64 = 4,
  kTfLiteString = 5,
  kTfLiteBool = 6,
  kTfLiteInt16 = 7,
  kTfLiteComplex64 = 8,
  kTfLiteInt8 = 9,
} TfLiteType;
```

**Comment by myungjoo** [comment]
Or... alternatively.. we may add ```nnstreamer.ini``` entry:

For example,
``` 
[tensorflow-lite]
support_bool_with_int8 = false
support_int8_with_int8 = true
# if support_bool_with_int8 == support_int8_with_int8 == true, it's an error and both will be turned off.
```

**Comment by ajarthurs** [comment]
I'm not sure support for `bool`-type tensors should be dropped for TF Lite versions 1.13 and up since they are specified in the [TF Lite V3 flatbuffers schema](https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/lite/schema/schema.fbs#L31:L43). I noticed the lack of `_NNS_BOOL` (or similar) or otherwise `tensor_filter_tensorflow_lite` interprets `bool`-type tensors as `int8` and not visa-versa. Are you planning on supporting `bool` later after adjusting for `int8`?

**Comment by myungjoo** [comment]
We will be able to support "_NNS_BOOL" if we can define a common data layout across different frameworks. In other words we will need some info on multiple frameworks (including tf/tflite) how they define "BOOL" types and how they pack tensors with "BOOL" types.

In the case of tflite/bool, although I don't remember exactly how/why we defined it, we made "BOOL" equivalent with int8 because it is packed as 8-bit data. If there are other "popular" frameworks that do 1-bit packaging for "BOOL" type, for the size efficiency, we won't be able to simply define "_NNS_BOOL" and let it behave as if it is INT8/UINT8.

As I already have a few clients giving us requirements (none of my clients have yet requested bool) and products to be implemented, we will be progressing slower than before., We do welcome contribution from the public including you :)

**Comment by ajarthurs** [comment]
@myungjoo I also haven't ran across `bool` tensors, at least not for quantized models, so I could take or leave `bool` for sake of testing. But, `bool`-type tensors seem unrelated to this issue.

Concerning the "hang" mentioned in my OP when running a quantized TF Lite model with an `uint8` I/O wrapper (internal tensors are `int8`), that turned out to be extremely slow inference; the model eventually finished with some detections. So, the only problem that concerns NNS is allowing for TF Lite models with `int8`-type I/O; otherwise, I would need to add I/O wrappers to my `int8` models.

Next task for me is to investigate the large difference in performance with `int8` vs `uint8` models, which is a TensorFlow issue.
