### ISSUE TITLE
[Static Analysis Result] Bugs to be fixed for v0.0.2 release

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#558]
- [x] L967,968 | gst/tensor_transform/tensor_transform.c | MyungJoo Ham
- [x] L246,247 | tests/bmp2png.c | MyungJoo Ham  
- [x] L98,99 | gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc | HyoungjooAhn  
- [x] L184,185 | nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c | Jaeyun  
- [x] L73,74 | nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler.c | MyungJoo Ham  
- [x] L55,56 | gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc | HyoungjooAhn  
- [x] L1055,1056 | nnstreamer_example/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c | Wook Song  
- [x] L488,489 | gst/tensor_mux/gsttensormux.c | jijoong.moon  
- [x] L287,288 | tests/bmp2png.c | MyungJoo Ham  
- [x] L221,222 | gst/tensor_split/gsttensorsplit.c | jijoong.moon  
- [x] L418,419 | nnstreamer_example/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c | Wook Song  
- [x] L190,191 | nnstreamer_example/custom_example_scaler/nnstreamer_customfilter_example_scaler_allocator.c | Jaeyun

**Comment by helloahn** [comment]
#566 

* **L98,99 | gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc | HyoungjooAhn**
Not initialized problem: solved at the new version because the parameters were removed.

* **L55,56 | gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc | HyoungjooAhn**
Not effective code: make the line as a comment for the future
