### ISSUE TITLE
[New Element or New Usage Case] Switch!

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#742]
It is like a circuit switch that connects or disconnects a power line (a stream pipeline)

```
SRC --> TEE --+--> QUEUE --> SWITCH:A --> T_FILTER:A --> T_SINK:A
              +--> QUEUE --> SWITCH:B --> T_FILTER:B --> T_SINK:B
```

On: it will simply pass incoming data (sink->src)
Off: it will not pass to its srcpad. any data coming to the sink will disappear (as if it's a sink element)

This may be implemented by prexisting elements.
We need to investigate current elements and possible usages that are equivalent to "SWITCH" before actually implementing it.

- [ ] TODO: Write WIKI Entry

**Comment by jaeyun-jung** [comment]
GstInputSelector (input-selector) : Direct one out of N input streams to the output pad.
GstOutputSelector (output-selector) : Direct input stream to one out of N output pads.
GstValve (valve) : The valve is a simple element that drops buffers when the GstValve:drop property is set to TRUE and lets then through otherwise.

**Comment by jaeyun-jung** [comment]
Maybe GstValve is the element you want.

**Comment by myungjoo** [comment]
Wow.. ```valve``` is exactly what I wanted. I'll write a Wiki entry for this because this has been one of the requirements from potential users.

**Comment by myungjoo** [comment]
Uh.. as GST already has one, we don't need this.
