### ISSUE TITLE
[AWS Kernel] v4l2loopback.ko: There is no media.ko kenel module

### ISSUE THREAD

**Issue by ohsewon** [nnsuite/nnstreamer#753]
kenel module is missng.
```bash
$ ls /lib/modules/`uname -r`/kernel/drivers/media
ls: cannot access '/lib/modules/`uname -r`/kernel/drivers/media': No such file or directory
```

**Comment by myungjoo** [comment]
Looks like the shell does not accept ``` ` ``` as noramlly bash does. Check the shell.

**Comment by leemgs** [comment]
I propose two approaches as follows to resolve  this issue. 
1. Reboot  Ubuntu instance with /boot/vmlinuz-4.4.0-138-generic  after getiing snapshot image to avoid unexpected accident. Caution: It will be critical at boot time
2. Keep /boot/vmlinuz-4.4.0-1067-aws. Instead, append manually required kernel modules (e.g., media.ko --> videodev.ko --> v4l2loopback.ko). Caution:    I do not recommed this approached because administrator can get  the more maintenance cost gradually. 
3. Any idea?

**Comment by myungjoo** [comment]
Let's go with 1. but with fallback kernel (aws default).
Refer: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UserProvidedKernels.html

**Comment by leemgs** [comment]
@ohsewon Can I start  the Step2 procedure from now on?

**Comment by leemgs** [comment]
* with Vanilla kernel (generic)
```bash
ubuntu@ip-172-31-27-164:~$ uname -a
Linux ip-172-31-27-164 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-27-164:~$ cat /proc/partitions
major minor  #blocks  name

 202        0  134217728 xvda
 202        1  134216687 xvda1
 202       80  268435456 xvdf
 202       81   33554432 xvdf1
 202       82  234880000 xvdf2
ubuntu@ip-172-31-27-164:~$

```

**Comment by leemgs** [comment]
Starting a mirroring test and live migration test between original instance and 2nd instance.

**Comment by leemgs** [comment]
Currently, work status is 60% to fix this issue. 
* https://github.com/nnsuite/nnstreamer/issues/753#issuecomment-435791316

**Comment by leemgs** [comment]
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UserProvidedKernels.html

The website above doe not provide how to use the "fallback" mechanism of Grub.  In order to switch back safely to previous versions due to kernel problems, refer to an official Grub website as following: 

* Grub: How to use "fallback" mechanism
   * https://www.gnu.org/software/grub/manual/legacy/Booting-fallback-systems.html

**Comment by ohsewon** [comment]
after booting AWS Ubuntu with generic-kernel, 'nnstreamer-apptest' is working well. 
done.
