### ISSUE TITLE
[Sync-Errors in Tensor_Repo] Possible deadlock / data inconsistency

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/nnstreamer#933]
By looking at the code again, I'm seeing possible sync-errors that may cause DEADLOCKs:

1. tensor_repo.c::gst_tensor_repo_add_repodata
```C
  GST_REPO_LOCK ();
  gpointer check = g_hash_table_lookup (_repo.hash, GINT_TO_POINTER (nth));

  if (check != NULL) {
    return TRUE;
}
```
You are returning without releasing the lock.

2. _repo.hash is often accessed without protection. You need to define which lock is protecting (GST_REPO_LOCK()??) and enforce using it whenever _repo.has is used.

3. When "nth" of _repo.hash is used, you need to ensure that nth's LOCK is ACQUIRED.

For 2.3., if an operation can be guaranteed to be atomic, it can be skipped with some special conditions, but it doesn't appear to be applicable in this code.

**Comment by jijoongmoon** [comment]
1. Return without Releasing. I fixed. (PR #934)
2. I think we do not need to get the _repo.hash lock except some cases.
   . remove and add nth TensorRepoData structure into hash table.
   . create and remove has table.
   For the access and wirte the GstBuffer, we could use TensorRepoData->lock and cond variables.
   In order to make sure set and get the buffer correctly, another cond variable is introduced. (cond_pull, cond_push : PR #922).
3. I concerned this when I wrote the code, but I will check again.
