### ISSUE TITLE
[unittest] model files for each NN frameworks.

### ISSUE THREAD

**Issue by helloahn** [nnsuite/nnstreamer#980]
Currently, the model file for the unit test is stored at `./tests/test_models/...`
To make the unit test for Tensorflow, we need to decide how to load the model files.

Shortly, we have 2 options.
1. store the model file at the same place, `./tests/test_models/...`
 -> it makes the size of our repository bigger. However it is the fastest way.
2. download model files from `testcases` repository
 -> it makes the size smaller but takes the long downloading time.

Which one should we take?

**Comment by myungjoo** [comment]
Model files > 10MB are better stored at our AWS storage.
Model files < 10MB may be located at testcases as well as AWS storage.

For unittesting, we'd better use extremely small models and such models can be exported from testing repository. (E.g., generate "nnstreamer-testcase-supplement.rpm" from testcase.git and use it with "BuildRequires" from nnstreamer.git. With a few options, you can make such unittest "optional" so that we can skip testing with such models if the supplement package is not avilable)

**Comment by myungjoo** [comment]
Anyway... it appears that even better approach is to create a VERY SMALL model (~ xx KB) and embed into /tests/* of nnstreamer.git.

**Comment by helloahn** [comment]
Ok, then.
1. model files, stored at this repository, will be changed to smaller one (not decided which one to use yet).
2. only examples will use the models of testcases repository.

**Comment by helloahn** [comment]
I found a tiny model, MNIST, I will make the test cases with this model.
